<a href="https://colab.research.google.com/github/juniperlovato/AASP/blob/main/AI_Art_Paper_Categorical_to_Ordinal_Kruskal_Wallis_5P.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#imports

In [57]:
!pip install pingouin


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 198.9/198.9 kB 1.5 MB/s eta 0:00:00


In [58]:
import numpy as np
import pandas as pd
from google.colab import files
import requests
import io
import seaborn as sns
import matplotlib as plt
import matplotlib.pyplot as plt
from scipy import stats
import statsmodels.api as sm
from scipy.stats import chi2_contingency
from statsmodels.graphics.mosaicplot import mosaic
from itertools import product
import seaborn as sns
from pingouin import kruskal, read_dataset

#data

In [21]:
#load data thats cleand ai_art_surveydata_cleaned.csv
Survey =  pd.read_csv('ai_art_surveydata_cleaned.csv')

In [22]:
Ordinal_Categorical_variables = Survey[['Artist', 'Gender_identity', 'Art_practice', 'AI_models_familiarity', 'Age', 'compensation',
                                        'Styleof_ownedby_AI_user', 'Styleof_ownedby_OG_artist', 'Styleof_ownedby_AI_company', 'Required_disclosure',
                                        'AI_pos_development_4art', 'AI_threat_2art_workers']]

#turning string values to numberical ones

In [23]:
#let'sc print out all the column names
for col_name in Ordinal_Categorical_variables.columns:
    print(col_name)

Artist
Gender_identity
Art_practice
AI_models_familiarity
Age
compensation
Styleof_ownedby_AI_user
Styleof_ownedby_OG_artist
Styleof_ownedby_AI_company
Required_disclosure
AI_pos_development_4art
AI_threat_2art_workers


In [24]:
Ordinal_Categorical_variables['Artist'].value_counts()

Artist
Yes             310
Somewhat        176
No                7
I’m not sure      2
Name: count, dtype: int64

In [25]:
# getting rid of answers I’m not sure
Ordinal_Categorical_variables = Ordinal_Categorical_variables[Ordinal_Categorical_variables["Artist"].str.contains("I’m not sure") == False]

In [26]:
Ordinal_Categorical_variables['Artist'].unique()

array(['No', 'Yes', 'Somewhat'], dtype=object)

In [27]:
Ordinal_Categorical_variables['Artist'] = np.where(Ordinal_Categorical_variables['Artist'] == 'Yes', 1, Ordinal_Categorical_variables['Artist'])
Ordinal_Categorical_variables['Artist'] = np.where(Ordinal_Categorical_variables['Artist'] == 'Somewhat', 1, Ordinal_Categorical_variables['Artist'])
Ordinal_Categorical_variables['Artist'] = np.where(Ordinal_Categorical_variables['Artist'] == 'No', 0, Ordinal_Categorical_variables['Artist'])
Ordinal_Categorical_variables['Artist'].value_counts()

Artist
1    486
0      7
Name: count, dtype: int64

In [28]:
Ordinal_Categorical_variables['Gender_identity'].value_counts()

Gender_identity
Male           273
Female         161
Non-binary      23
Name: count, dtype: int64

In [29]:
Ordinal_Categorical_variables['Gender_identity'] = np.where(Ordinal_Categorical_variables['Gender_identity'] == 'Male', 1.0, Ordinal_Categorical_variables['Gender_identity'])
Ordinal_Categorical_variables['Gender_identity'] = np.where(Ordinal_Categorical_variables['Gender_identity'] == 'Female', 2.0, Ordinal_Categorical_variables['Gender_identity'])
Ordinal_Categorical_variables['Gender_identity'] = np.where(Ordinal_Categorical_variables['Gender_identity'] == 'Non-binary ', 3.0, Ordinal_Categorical_variables['Gender_identity'])
Ordinal_Categorical_variables['Gender_identity']

0      2.0
1      2.0
2      2.0
3      2.0
4      2.0
      ... 
508    1.0
509    1.0
510    2.0
511    2.0
512    1.0
Name: Gender_identity, Length: 493, dtype: object

In [30]:
Ordinal_Categorical_variables['Art_practice'].value_counts()

Art_practice
paint           167
Photography     115
writing          52
designer         42
craft            20
music            18
digital          14
not artist       13
other            11
tattoo            9
illustration      9
drawing           8
sculpture         7
maker             5
Name: count, dtype: int64

In [31]:
Ordinal_Categorical_variables['Art_practice'] = np.where(Ordinal_Categorical_variables['Art_practice'] == 'paint', 1, Ordinal_Categorical_variables['Art_practice'])
Ordinal_Categorical_variables['Art_practice'] = np.where(Ordinal_Categorical_variables['Art_practice'] == 'Photography', 2, Ordinal_Categorical_variables['Art_practice'])
Ordinal_Categorical_variables['Art_practice'] = np.where(Ordinal_Categorical_variables['Art_practice'] == 'writing', 3, Ordinal_Categorical_variables['Art_practice'])
Ordinal_Categorical_variables['Art_practice'] = np.where(Ordinal_Categorical_variables['Art_practice'] == 'designer', 4, Ordinal_Categorical_variables['Art_practice'])
Ordinal_Categorical_variables['Art_practice'] = np.where(Ordinal_Categorical_variables['Art_practice'] == 'craft', 5, Ordinal_Categorical_variables['Art_practice'])
Ordinal_Categorical_variables['Art_practice'] = np.where(Ordinal_Categorical_variables['Art_practice'] == 'music', 6, Ordinal_Categorical_variables['Art_practice'])
Ordinal_Categorical_variables['Art_practice'] = np.where(Ordinal_Categorical_variables['Art_practice'] == 'digital', 7, Ordinal_Categorical_variables['Art_practice'])
Ordinal_Categorical_variables['Art_practice'] = np.where(Ordinal_Categorical_variables['Art_practice'] == 'not artist', 8, Ordinal_Categorical_variables['Art_practice'])
Ordinal_Categorical_variables['Art_practice'] = np.where(Ordinal_Categorical_variables['Art_practice'] == 'other', 9, Ordinal_Categorical_variables['Art_practice'])
Ordinal_Categorical_variables['Art_practice'] = np.where(Ordinal_Categorical_variables['Art_practice'] == 'tattoo', 10, Ordinal_Categorical_variables['Art_practice'])
Ordinal_Categorical_variables['Art_practice'] = np.where(Ordinal_Categorical_variables['Art_practice'] == 'illustration', 11, Ordinal_Categorical_variables['Art_practice'])
Ordinal_Categorical_variables['Art_practice'] = np.where(Ordinal_Categorical_variables['Art_practice'] == 'drawing', 12, Ordinal_Categorical_variables['Art_practice'])
Ordinal_Categorical_variables['Art_practice'] = np.where(Ordinal_Categorical_variables['Art_practice'] == 'sculpture', 13, Ordinal_Categorical_variables['Art_practice'])
Ordinal_Categorical_variables['Art_practice'] = np.where(Ordinal_Categorical_variables['Art_practice'] == 'maker', 14, Ordinal_Categorical_variables['Art_practice'])
Ordinal_Categorical_variables['Art_practice'].value_counts()

Art_practice
1     167
2     115
3      52
4      42
5      20
6      18
7      14
8      13
9      11
10      9
11      9
12      8
13      7
14      5
Name: count, dtype: int64

In [32]:
Ordinal_Categorical_variables['AI_models_familiarity'].value_counts()

AI_models_familiarity
AI art generally        377
none                     44
AI_Deeplearning_GANS     42
text to image            12
LLMS                      5
Name: count, dtype: int64

In [33]:
Ordinal_Categorical_variables['AI_models_familiarity'] = np.where(Ordinal_Categorical_variables['AI_models_familiarity'] == 'AI art generally', 1, Ordinal_Categorical_variables['AI_models_familiarity'])
Ordinal_Categorical_variables['AI_models_familiarity'] = np.where(Ordinal_Categorical_variables['AI_models_familiarity'] == 'none', 2, Ordinal_Categorical_variables['AI_models_familiarity'])
Ordinal_Categorical_variables['AI_models_familiarity'] = np.where(Ordinal_Categorical_variables['AI_models_familiarity'] == 'AI_Deeplearning_GANS', 3, Ordinal_Categorical_variables['AI_models_familiarity'])
Ordinal_Categorical_variables['AI_models_familiarity'] = np.where(Ordinal_Categorical_variables['AI_models_familiarity'] == 'text to image', 4, Ordinal_Categorical_variables['AI_models_familiarity'])
Ordinal_Categorical_variables['AI_models_familiarity'] = np.where(Ordinal_Categorical_variables['AI_models_familiarity'] == 'LLMS', 5, Ordinal_Categorical_variables['AI_models_familiarity'])
Ordinal_Categorical_variables['AI_models_familiarity'].value_counts()

AI_models_familiarity
1    377
2     44
3     42
4     12
5      5
Name: count, dtype: int64

In [34]:
Ordinal_Categorical_variables['Age'].value_counts()

Age
30-49          231
18 - 29        104
50-64           79
65 or older     43
Name: count, dtype: int64

In [35]:
Ordinal_Categorical_variables['Age'] = np.where(Ordinal_Categorical_variables['Age'] == '30-49', 1, Ordinal_Categorical_variables['Age'])
Ordinal_Categorical_variables['Age'] = np.where(Ordinal_Categorical_variables['Age'] == '18 - 29', 2, Ordinal_Categorical_variables['Age'])
Ordinal_Categorical_variables['Age'] = np.where(Ordinal_Categorical_variables['Age'] == '50-64', 3, Ordinal_Categorical_variables['Age'])
Ordinal_Categorical_variables['Age'] = np.where(Ordinal_Categorical_variables['Age'] == '65 or older', 4, Ordinal_Categorical_variables['Age'])
Ordinal_Categorical_variables['Age'].value_counts()

Age
1    231
2    104
3     79
4     43
Name: count, dtype: int64

In [36]:
Ordinal_Categorical_variables['compensation'].unique()

array(['tax', 'not_comfortable_with_any_listed_options',
       'nocomp_but_no_forprofit', 'flat_fee', 'donate_to_trainer',
       'nocompt_noprofit4anyone', 'Other', 'portion_from_derivatives',
       'portion_of_any_profit_made', 'portion_from_model_creators',
       'I_dont_need_profit', nan], dtype=object)

In [37]:
Ordinal_Categorical_variables['compensation'] = np.where(Ordinal_Categorical_variables['compensation'] == 'tax', 1, Ordinal_Categorical_variables['compensation'])
Ordinal_Categorical_variables['compensation'] = np.where(Ordinal_Categorical_variables['compensation'] == 'not_comfortable_with_any_listed_options', 2, Ordinal_Categorical_variables['compensation'])
Ordinal_Categorical_variables['compensation'] = np.where(Ordinal_Categorical_variables['compensation'] == 'nocomp_but_no_forprofit', 3, Ordinal_Categorical_variables['compensation'])
Ordinal_Categorical_variables['compensation'] = np.where(Ordinal_Categorical_variables['compensation'] == 'flat_fee', 4, Ordinal_Categorical_variables['compensation'])
Ordinal_Categorical_variables['compensation'] = np.where(Ordinal_Categorical_variables['compensation'] == 'donate_to_trainer', 5, Ordinal_Categorical_variables['compensation'])
Ordinal_Categorical_variables['compensation'] = np.where(Ordinal_Categorical_variables['compensation'] == 'nocompt_noprofit4anyone', 6, Ordinal_Categorical_variables['compensation'])
Ordinal_Categorical_variables['compensation'] = np.where(Ordinal_Categorical_variables['compensation'] == 'Other', 7, Ordinal_Categorical_variables['compensation'])
Ordinal_Categorical_variables['compensation'] = np.where(Ordinal_Categorical_variables['compensation'] == 'portion_from_derivatives', 8, Ordinal_Categorical_variables['compensation'])
Ordinal_Categorical_variables['compensation'] = np.where(Ordinal_Categorical_variables['compensation'] == 'portion_of_any_profit_made', 9, Ordinal_Categorical_variables['compensation'])
Ordinal_Categorical_variables['compensation'] = np.where(Ordinal_Categorical_variables['compensation'] == 'portion_from_model_creators', 10, Ordinal_Categorical_variables['compensation'])
Ordinal_Categorical_variables['compensation'] = np.where(Ordinal_Categorical_variables['compensation'] == 'I_dont_need_profit', 11, Ordinal_Categorical_variables['compensation'])
Ordinal_Categorical_variables['compensation'].value_counts()

compensation
3     106
5      81
4      54
10     51
2      42
8      32
9      32
6      27
11     22
7      10
1       6
Name: count, dtype: int64

#making contingency tables

In [39]:
#selecting the columns I want to use for analysis

Ordinal_Categorical_variables_results = pd.DataFrame()

Ordinal_Categorical_variables_results['variable_combo'] = ['SO_owned_AIuser_Artist', 'SO_owned_AIuser_Gender', 'SO_owned_AIuser_Art_prac','SO_owned_AIuser_AI_models_fam','SO_owned_AIuser_Age','SO_owned_AIuser_Fair_comp',
                                                           'SO_owned_OGartist_Artist',  'SO_owned_OGartist_Gender','SO_owned_OGartist_Art_prac','SO_owned_OGartist_AI_models_fam','SO_owned_OGartist_Age','SO_owned_OGartist_Fair_comp',
                                                           'SO_owned_AIcom_Artist','SO_owned_AIcom_Gender','SO_owned_AIcom_Art_prac','SO_owned_AIcom_AI_models_fam','SO_owned_AIcom_Age','SO_owned_AIcom_Fair_comp',
                                                           'Req_disclos_Artist','Req_disclos_Gender','Req_disclos_Art_prac','Req_disclos_AI_models_fam','Req_disclos_Age','Req_disclos_Fair_comp',
                                                           'AI_pos_dev_Artist', 'AI_pos_dev_Gender', 'AI_pos_dev_Art_prac', 'AI_pos_dev_AI_models_fam', 'AI_pos_dev_Age', 'AI_pos_dev_Fair_comp',
                                                           'AI_threat_Artist', 'AI_threat_Gender', 'AI_threat_Art_prac', 'AI_threat_AI_models_fam', 'AI_threat_Age', 'AI_threat_Fair_comp',

                                                           ]


In [41]:
#creating an empty column for a contingency table
Ordinal_Categorical_variables_results['contingency_table'] = ""

In [42]:
#make a contingency table out of our variables
SO_owned_AIuser_Artist = pd.crosstab(Ordinal_Categorical_variables['Artist'], Ordinal_Categorical_variables['Styleof_ownedby_AI_user'], dropna=False, normalize='index')
SO_owned_AIuser_Gender = pd.crosstab(Ordinal_Categorical_variables['Gender_identity'], Ordinal_Categorical_variables['Styleof_ownedby_AI_user'], dropna=False, normalize='index')
SO_owned_AIuser_Art_prac = pd.crosstab(Ordinal_Categorical_variables['Art_practice'], Ordinal_Categorical_variables['Styleof_ownedby_AI_user'], dropna=False, normalize='index')
SO_owned_AIuser_AI_models_fam = pd.crosstab(Ordinal_Categorical_variables['AI_models_familiarity'], Ordinal_Categorical_variables['Styleof_ownedby_AI_user'], dropna=False, normalize='index')
SO_owned_AIuser_Age = pd.crosstab(Ordinal_Categorical_variables['Age'], Ordinal_Categorical_variables['Styleof_ownedby_AI_user'], dropna=False, normalize='index')
SO_owned_AIuser_Fair_comp = pd.crosstab(Ordinal_Categorical_variables['compensation'], Ordinal_Categorical_variables['Styleof_ownedby_AI_user'], dropna=False, normalize='index')

#I want to save these as an array for the data frame later on
SO_owned_AIuser_Artist_contingency = SO_owned_AIuser_Artist.values
SO_owned_AIuser_Gender_contingency = SO_owned_AIuser_Gender.values
SO_owned_AIuser_Art_prac_contingency = SO_owned_AIuser_Art_prac.values
SO_owned_AIuser_AI_models_fam_contingency = SO_owned_AIuser_AI_models_fam.values
SO_owned_AIuser_Age_contingency = SO_owned_AIuser_Age.values
SO_owned_AIuser_Fair_comp_contingency = SO_owned_AIuser_Fair_comp.values

In [43]:
#checking it works
print(SO_owned_AIuser_Artist_contingency)

[[0.16666667 0.         0.66666667 0.16666667 0.        ]
 [0.19006479 0.22030238 0.20302376 0.20518359 0.18142549]]


In [44]:
#checking it works
SO_owned_AIuser_Artist

Styleof_ownedby_AI_user       1.0       2.0       3.0       4.0       5.0
Artist                                                                   
0                        0.166667  0.000000  0.666667  0.166667  0.000000
1                        0.190065  0.220302  0.203024  0.205184  0.181425

In [45]:
#make a contingency table out of our variables
SO_owned_OGartist_Artist = pd.crosstab(Ordinal_Categorical_variables['Artist'], Ordinal_Categorical_variables['Styleof_ownedby_OG_artist'], dropna=False, normalize='index')
SO_owned_OGartist_Gender = pd.crosstab(Ordinal_Categorical_variables['Gender_identity'], Ordinal_Categorical_variables['Styleof_ownedby_OG_artist'], dropna=False, normalize='index')
SO_owned_OGartist_Art_prac = pd.crosstab(Ordinal_Categorical_variables['Art_practice'], Ordinal_Categorical_variables['Styleof_ownedby_OG_artist'], dropna=False, normalize='index')
SO_owned_OGartist_AI_models_fam = pd.crosstab(Ordinal_Categorical_variables['AI_models_familiarity'], Ordinal_Categorical_variables['Styleof_ownedby_OG_artist'], dropna=False, normalize='index')
SO_owned_OGartist_Age = pd.crosstab(Ordinal_Categorical_variables['Age'], Ordinal_Categorical_variables['Styleof_ownedby_OG_artist'], dropna=False, normalize='index')
SO_owned_OGartist_Fair_comp = pd.crosstab(Ordinal_Categorical_variables['compensation'], Ordinal_Categorical_variables['Styleof_ownedby_OG_artist'], dropna=False, normalize='index')

#I want to save these as an array for the data frame later on
SO_owned_OGartist_Artist_contingency = SO_owned_OGartist_Artist.values
SO_owned_OGartist_Gender_contingency = SO_owned_OGartist_Gender.values
SO_owned_OGartist_Art_prac_contingency = SO_owned_OGartist_Art_prac.values
SO_owned_OGartist_AI_models_fam_contingency = SO_owned_OGartist_AI_models_fam.values
SO_owned_OGartist_Age_contingency = SO_owned_OGartist_Age.values
SO_owned_OGartist_Fair_comp_contingency = SO_owned_OGartist_Fair_comp.values

In [46]:
#make a contingency table out of our variables
SO_owned_AIcom_Artist = pd.crosstab(Ordinal_Categorical_variables['Artist'], Ordinal_Categorical_variables['Styleof_ownedby_AI_company'], dropna=False, normalize='index')
SO_owned_AIcom_Gender = pd.crosstab(Ordinal_Categorical_variables['Gender_identity'], Ordinal_Categorical_variables['Styleof_ownedby_AI_company'], dropna=False, normalize='index')
SO_owned_AIcom_Art_prac = pd.crosstab(Ordinal_Categorical_variables['Art_practice'], Ordinal_Categorical_variables['Styleof_ownedby_AI_company'], dropna=False, normalize='index')
SO_owned_AIcom_AI_models_fam = pd.crosstab(Ordinal_Categorical_variables['AI_models_familiarity'], Ordinal_Categorical_variables['Styleof_ownedby_AI_company'], dropna=False, normalize='index')
SO_owned_AIcom_Age = pd.crosstab(Ordinal_Categorical_variables['Age'], Ordinal_Categorical_variables['Styleof_ownedby_AI_company'], dropna=False, normalize='index')
SO_owned_AIcom_Fair_comp = pd.crosstab(Ordinal_Categorical_variables['compensation'], Ordinal_Categorical_variables['Styleof_ownedby_AI_company'], dropna=False, normalize='index')

#I want to save these as an array for the data frame later on
SO_owned_AIcom_Artist_contingency = SO_owned_AIcom_Artist.values
SO_owned_AIcom_Gender_contingency = SO_owned_AIcom_Gender.values
SO_owned_AIcom_Art_prac_contingency = SO_owned_AIcom_Art_prac.values
SO_owned_AIcom_AI_models_fam_contingency = SO_owned_AIcom_AI_models_fam.values
SO_owned_AIcom_Age_contingency = SO_owned_AIcom_Age.values
SO_owned_AIcom_Fair_comp_contingency = SO_owned_AIcom_Fair_comp.values

In [47]:
#make a contingency table out of our variables

Req_disclos_Artist = pd.crosstab(Ordinal_Categorical_variables['Artist'], Ordinal_Categorical_variables['Required_disclosure'], dropna=False, normalize='index')
Req_disclos_Gender = pd.crosstab(Ordinal_Categorical_variables['Gender_identity'], Ordinal_Categorical_variables['Required_disclosure'], dropna=False, normalize='index')
Req_disclos_Art_prac = pd.crosstab(Ordinal_Categorical_variables['Art_practice'], Ordinal_Categorical_variables['Required_disclosure'], dropna=False, normalize='index')
Req_disclos_AI_models_fam = pd.crosstab(Ordinal_Categorical_variables['AI_models_familiarity'], Ordinal_Categorical_variables['Required_disclosure'], dropna=False, normalize='index')
Req_disclos_Age = pd.crosstab(Ordinal_Categorical_variables['Age'], Ordinal_Categorical_variables['Required_disclosure'], dropna=False, normalize='index')
Req_disclos_Fair_comp = pd.crosstab(Ordinal_Categorical_variables['compensation'], Ordinal_Categorical_variables['Required_disclosure'], dropna=False, normalize='index')

#I want to save these as an array for the data frame later on
Req_disclos_Artist_contingency = Req_disclos_Artist.values
Req_disclos_Gender_contingency = Req_disclos_Gender.values
Req_disclos_Art_prac_contingency = Req_disclos_Art_prac.values
Req_disclos_AI_models_fam_contingency = Req_disclos_AI_models_fam.values
Req_disclos_Age_contingency = Req_disclos_Age.values
Req_disclos_Fair_comp_contingency = Req_disclos_Fair_comp.values

In [48]:
#make a contingency table out of our variables

AI_pos_dev_Artist = pd.crosstab(Ordinal_Categorical_variables['Artist'], Ordinal_Categorical_variables['AI_pos_development_4art'], dropna=False, normalize='index')
AI_pos_dev_Gender = pd.crosstab(Ordinal_Categorical_variables['Gender_identity'], Ordinal_Categorical_variables['AI_pos_development_4art'], dropna=False, normalize='index')
AI_pos_dev_Art_prac = pd.crosstab(Ordinal_Categorical_variables['Art_practice'], Ordinal_Categorical_variables['AI_pos_development_4art'], dropna=False, normalize='index')
AI_pos_dev_AI_models_fam = pd.crosstab(Ordinal_Categorical_variables['AI_models_familiarity'], Ordinal_Categorical_variables['AI_pos_development_4art'], dropna=False, normalize='index')
AI_pos_dev_Age = pd.crosstab(Ordinal_Categorical_variables['Age'], Ordinal_Categorical_variables['AI_pos_development_4art'], dropna=False, normalize='index')
AI_pos_dev_Fair_comp = pd.crosstab(Ordinal_Categorical_variables['compensation'], Ordinal_Categorical_variables['AI_pos_development_4art'], dropna=False, normalize='index')

#I want to save these as an array for the data frame later on
AI_pos_dev_Artist_contingency = AI_pos_dev_Artist.values
AI_pos_dev_Gender_contingency = AI_pos_dev_Gender.values
AI_pos_dev_Art_prac_contingency = AI_pos_dev_Art_prac.values
AI_pos_dev_AI_models_fam_contingency = AI_pos_dev_AI_models_fam.values
AI_pos_dev_Age_contingency = AI_pos_dev_Age.values
AI_pos_dev_Fair_comp_contingency = AI_pos_dev_Fair_comp.values

In [49]:
#make a contingency table out of our variables

AI_threat_Artist = pd.crosstab(Ordinal_Categorical_variables['Artist'], Ordinal_Categorical_variables['AI_threat_2art_workers'], dropna=False, normalize='index')
AI_threat_Gender = pd.crosstab(Ordinal_Categorical_variables['Gender_identity'], Ordinal_Categorical_variables['AI_threat_2art_workers'], dropna=False, normalize='index')
AI_threat_Art_prac = pd.crosstab(Ordinal_Categorical_variables['Art_practice'], Ordinal_Categorical_variables['AI_threat_2art_workers'], dropna=False, normalize='index')
AI_threat_AI_models_fam = pd.crosstab(Ordinal_Categorical_variables['AI_models_familiarity'], Ordinal_Categorical_variables['AI_threat_2art_workers'], dropna=False, normalize='index')
AI_threat_Age = pd.crosstab(Ordinal_Categorical_variables['Age'], Ordinal_Categorical_variables['AI_threat_2art_workers'], dropna=False, normalize='index')
AI_threat_Fair_comp = pd.crosstab(Ordinal_Categorical_variables['compensation'], Ordinal_Categorical_variables['AI_threat_2art_workers'], dropna=False, normalize='index')

#I want to save these as an array for the data frame later on
AI_threat_Artist_contingency = AI_threat_Artist.values
AI_threat_Gender_contingency = AI_threat_Gender.values
AI_threat_Art_prac_contingency = AI_threat_Art_prac.values
AI_threat_AI_models_fam_contingency = AI_threat_AI_models_fam.values
AI_threat_Age_contingency = AI_threat_Age.values
AI_threat_Fair_comp_contingency = AI_threat_Fair_comp.values

In [50]:
print(AI_threat_Artist_contingency, AI_threat_Gender_contingency)

[[0.         0.2        0.4        0.2        0.2       ]
 [0.0619469  0.14159292 0.17256637 0.34070796 0.28318584]] [[0.04779412 0.15441176 0.18014706 0.33823529 0.27941176]
 [0.07453416 0.1242236  0.17391304 0.31677019 0.31055901]
 [0.13043478 0.13043478 0.08695652 0.52173913 0.13043478]]


In [55]:
#adding these contingency tables to my new column
Ordinal_Categorical_variables_results['contingency_table'] = [SO_owned_AIuser_Artist_contingency , SO_owned_AIuser_Gender_contingency , SO_owned_AIuser_Art_prac_contingency ,SO_owned_AIuser_AI_models_fam_contingency ,SO_owned_AIuser_Age_contingency ,SO_owned_AIuser_Fair_comp_contingency ,
SO_owned_OGartist_Artist_contingency , SO_owned_OGartist_Gender_contingency ,SO_owned_OGartist_Art_prac_contingency ,SO_owned_OGartist_AI_models_fam_contingency ,SO_owned_OGartist_Age_contingency ,SO_owned_OGartist_Fair_comp_contingency ,
SO_owned_AIcom_Artist_contingency ,SO_owned_AIcom_Gender_contingency ,SO_owned_AIcom_Art_prac_contingency ,SO_owned_AIcom_AI_models_fam_contingency ,SO_owned_AIcom_Age_contingency ,SO_owned_AIcom_Fair_comp_contingency ,
Req_disclos_Artist_contingency ,Req_disclos_Gender_contingency ,Req_disclos_Art_prac_contingency ,Req_disclos_AI_models_fam_contingency ,Req_disclos_Age_contingency ,Req_disclos_Fair_comp_contingency ,
AI_pos_dev_Artist_contingency , AI_pos_dev_Gender_contingency , AI_pos_dev_Art_prac_contingency , AI_pos_dev_AI_models_fam_contingency , AI_pos_dev_Age_contingency , AI_pos_dev_Fair_comp_contingency ,
AI_threat_Artist_contingency , AI_threat_Gender_contingency , AI_threat_Art_prac_contingency , AI_threat_AI_models_fam_contingency , AI_threat_Age_contingency , AI_threat_Fair_comp_contingency ,]



In [56]:
print(AI_pos_dev_Age_contingency)
AI_pos_dev_Age
#matched up good

[[0.09565217 0.14347826 0.26086957 0.25652174 0.24347826]
 [0.19230769 0.18269231 0.21153846 0.19230769 0.22115385]
 [0.15189873 0.11392405 0.3164557  0.18987342 0.2278481 ]
 [0.13953488 0.18604651 0.39534884 0.20930233 0.06976744]]


AI_pos_development_4art       1.0       2.0       3.0       4.0       5.0
Age                                                                      
1                        0.095652  0.143478  0.260870  0.256522  0.243478
2                        0.192308  0.182692  0.211538  0.192308  0.221154
3                        0.151899  0.113924  0.316456  0.189873  0.227848
4                        0.139535  0.186047  0.395349  0.209302  0.069767

In [59]:
Ordinal_Categorical_variables = Ordinal_Categorical_variables.dropna()

In [60]:
Ordinal_Categorical_variables['Gender_identity'] = Ordinal_Categorical_variables['Gender_identity'].astype(int)
Ordinal_Categorical_variables['Artist'] = Ordinal_Categorical_variables['Artist'].astype(int)
Ordinal_Categorical_variables['Art_practice'] = Ordinal_Categorical_variables['Art_practice'].astype(int)
Ordinal_Categorical_variables['AI_models_familiarity'] = Ordinal_Categorical_variables['AI_models_familiarity'].astype(int)
Ordinal_Categorical_variables['compensation'] = Ordinal_Categorical_variables['compensation'].astype(int)
Ordinal_Categorical_variables['Age'] = Ordinal_Categorical_variables['Age'].astype(int)

In [61]:
Ordinal_Categorical_variables['AI_pos_development_4art'] = Ordinal_Categorical_variables['AI_pos_development_4art'].astype(int)
Ordinal_Categorical_variables['AI_pos_development_4art']
Ordinal_Categorical_variables['Age']

0      3
1      3
2      3
3      4
4      1
      ..
508    1
509    3
510    1
511    1
512    3
Name: Age, Length: 454, dtype: int64

#Kruskal Wallis

Kruskal wallis 1 https://pingouin-stats.org/build/html/generated/pingouin.kruskal.html

In [62]:
#checking that the results are the same in two different KW test modules and they are phew!


Group1 = Ordinal_Categorical_variables.loc[Ordinal_Categorical_variables['Age'] == 1, 'AI_pos_development_4art']
Group2 = Ordinal_Categorical_variables.loc[Ordinal_Categorical_variables['Age'] == 2, 'AI_pos_development_4art']
Group3 = Ordinal_Categorical_variables.loc[Ordinal_Categorical_variables['Age'] == 3, 'AI_pos_development_4art']
Group4 = Ordinal_Categorical_variables.loc[Ordinal_Categorical_variables['Age'] == 4, 'AI_pos_development_4art']


stats.kruskal(Group1, Group2, Group3, Group4)


KruskalResult(statistic=8.345451383127612, pvalue=0.039386563646953844)

In [63]:
#kw # 2

kruskal(data=Ordinal_Categorical_variables, dv='AI_pos_development_4art', between='Age')




Source  ddof1         H     p-unc
Kruskal    Age      3  8.345451  0.039387

In [64]:
#Running the Kruskal Wallis
SO_owned_AIuser_Artist_KW = kruskal(data=Ordinal_Categorical_variables, dv='Styleof_ownedby_AI_user', between='Artist')
SO_owned_AIuser_Gender_KW = kruskal(data=Ordinal_Categorical_variables, dv='Styleof_ownedby_AI_user', between='Gender_identity')
SO_owned_AIuser_Art_prac_KW = kruskal(data=Ordinal_Categorical_variables, dv='Styleof_ownedby_AI_user', between='Art_practice')
SO_owned_AIuser_AI_models_fam_KW = kruskal(data=Ordinal_Categorical_variables, dv='Styleof_ownedby_AI_user', between='AI_models_familiarity')
SO_owned_AIuser_Age_KW = kruskal(data=Ordinal_Categorical_variables, dv='Styleof_ownedby_AI_user', between='Age')
SO_owned_AIuser_Fair_comp_KW = kruskal(data=Ordinal_Categorical_variables, dv='Styleof_ownedby_AI_user', between='compensation')


SO_owned_OGartist_Artist_KW = kruskal(data=Ordinal_Categorical_variables, dv='Styleof_ownedby_OG_artist', between='Artist')
SO_owned_OGartist_Gender_KW = kruskal(data=Ordinal_Categorical_variables, dv='Styleof_ownedby_OG_artist', between='Gender_identity')
SO_owned_OGartist_Art_prac_KW = kruskal(data=Ordinal_Categorical_variables, dv='Styleof_ownedby_OG_artist', between='Art_practice')
SO_owned_OGartist_AI_models_fam_KW = kruskal(data=Ordinal_Categorical_variables, dv='Styleof_ownedby_OG_artist', between='AI_models_familiarity')
SO_owned_OGartist_Age_KW = kruskal(data=Ordinal_Categorical_variables, dv='Styleof_ownedby_OG_artist', between='Age')
SO_owned_OGartist_Fair_comp_KW = kruskal(data=Ordinal_Categorical_variables, dv='Styleof_ownedby_OG_artist', between='compensation')


SO_owned_AIcom_Artist_KW = kruskal(data=Ordinal_Categorical_variables, dv='Styleof_ownedby_AI_company', between='Artist')
SO_owned_AIcom_Gender_KW = kruskal(data=Ordinal_Categorical_variables, dv='Styleof_ownedby_AI_company', between='Gender_identity')
SO_owned_AIcom_Art_prac_KW = kruskal(data=Ordinal_Categorical_variables, dv='Styleof_ownedby_AI_company', between='Art_practice')
SO_owned_AIcom_AI_models_fam_KW = kruskal(data=Ordinal_Categorical_variables, dv='Styleof_ownedby_AI_company', between='AI_models_familiarity')
SO_owned_AIcom_Age_KW = kruskal(data=Ordinal_Categorical_variables, dv='Styleof_ownedby_AI_company', between='Age')
SO_owned_AIcom_Fair_comp_KW = kruskal(data=Ordinal_Categorical_variables, dv='Styleof_ownedby_AI_company', between='compensation')


Req_disclos_Artist_KW = kruskal(data=Ordinal_Categorical_variables, dv='Required_disclosure', between='Artist')
Req_disclos_Gender_KW = kruskal(data=Ordinal_Categorical_variables, dv='Required_disclosure', between='Gender_identity')
Req_disclos_Art_prac_KW = kruskal(data=Ordinal_Categorical_variables, dv='Required_disclosure', between='Art_practice')
Req_disclos_AI_models_fam_KW = kruskal(data=Ordinal_Categorical_variables, dv='Required_disclosure', between='AI_models_familiarity')
Req_disclos_Age_KW = kruskal(data=Ordinal_Categorical_variables, dv='Required_disclosure', between='Age')
Req_disclos_Fair_comp_KW = kruskal(data=Ordinal_Categorical_variables, dv='Required_disclosure', between='compensation')


AI_pos_dev_Artist_KW = kruskal(data=Ordinal_Categorical_variables, dv='AI_pos_development_4art', between='Artist')
AI_pos_dev_Gender_KW = kruskal(data=Ordinal_Categorical_variables, dv='AI_pos_development_4art', between='Gender_identity')
AI_pos_dev_Art_prac_KW = kruskal(data=Ordinal_Categorical_variables, dv='AI_pos_development_4art', between='Art_practice')
AI_pos_dev_AI_models_fam_KW = kruskal(data=Ordinal_Categorical_variables, dv='AI_pos_development_4art', between='AI_models_familiarity')
AI_pos_dev_Age_KW = kruskal(data=Ordinal_Categorical_variables, dv='AI_pos_development_4art', between='Age')
AI_pos_dev_Fair_comp_KW = kruskal(data=Ordinal_Categorical_variables, dv='AI_pos_development_4art', between='compensation')


AI_threat_Artist_KW = kruskal(data=Ordinal_Categorical_variables, dv='AI_threat_2art_workers', between='Artist')
AI_threat_Gender_KW = kruskal(data=Ordinal_Categorical_variables, dv='AI_threat_2art_workers', between='Gender_identity')
AI_threat_Art_prac_KW = kruskal(data=Ordinal_Categorical_variables, dv='AI_threat_2art_workers', between='Art_practice')
AI_threat_AI_models_fam_KW = kruskal(data=Ordinal_Categorical_variables, dv='AI_threat_2art_workers', between='AI_models_familiarity')
AI_threat_Age_KW = kruskal(data=Ordinal_Categorical_variables, dv='AI_threat_2art_workers', between='Age')
AI_threat_Fair_comp_KW = kruskal(data=Ordinal_Categorical_variables, dv='AI_threat_2art_workers', between='compensation')


In [66]:
Ordinal_Categorical_variables_KW = pd.concat([SO_owned_AIuser_Artist_KW, SO_owned_AIuser_Gender_KW , SO_owned_AIuser_Art_prac_KW ,SO_owned_AIuser_AI_models_fam_KW ,SO_owned_AIuser_Age_KW ,SO_owned_AIuser_Fair_comp_KW ,
SO_owned_OGartist_Artist_KW , SO_owned_OGartist_Gender_KW ,SO_owned_OGartist_Art_prac_KW ,SO_owned_OGartist_AI_models_fam_KW ,SO_owned_OGartist_Age_KW ,SO_owned_OGartist_Fair_comp_KW ,
SO_owned_AIcom_Artist_KW ,SO_owned_AIcom_Gender_KW ,SO_owned_AIcom_Art_prac_KW ,SO_owned_AIcom_AI_models_fam_KW ,SO_owned_AIcom_Age_KW ,SO_owned_AIcom_Fair_comp_KW ,
Req_disclos_Artist_KW ,Req_disclos_Gender_KW ,Req_disclos_Art_prac_KW ,Req_disclos_AI_models_fam_KW ,Req_disclos_Age_KW ,Req_disclos_Fair_comp_KW ,
AI_pos_dev_Artist_KW , AI_pos_dev_Gender_KW , AI_pos_dev_Art_prac_KW , AI_pos_dev_AI_models_fam_KW , AI_pos_dev_Age_KW , AI_pos_dev_Fair_comp_KW ,
AI_threat_Artist_KW , AI_threat_Gender_KW , AI_threat_Art_prac_KW , AI_threat_AI_models_fam_KW , AI_threat_Age_KW , AI_threat_Fair_comp_KW], axis=0, ignore_index=True)

#make sure it worked
Ordinal_Categorical_variables_KW.head()


Source  ddof1          H     p-unc
0                 Artist      1   0.067037  0.795701
1        Gender_identity      2  19.650716  0.000054
2           Art_practice     13  17.971415  0.158608
3  AI_models_familiarity      4   6.531461  0.162819
4                    Age      3   2.547225  0.466817

In [68]:
#Combining the results into one dataframe
Ordinal_Categorical_variables_results = pd.concat([Ordinal_Categorical_variables_results, Ordinal_Categorical_variables_KW], axis =1)
Ordinal_Categorical_variables_results.head()

variable_combo  \
0         SO_owned_AIuser_Artist   
1         SO_owned_AIuser_Gender   
2       SO_owned_AIuser_Art_prac   
3  SO_owned_AIuser_AI_models_fam   
4            SO_owned_AIuser_Age   

                                   contingency_table                 Source  \
0  [[0.16666666666666666, 0.0, 0.6666666666666666...                 Artist   
1  [[0.13186813186813187, 0.1978021978021978, 0.2...        Gender_identity   
2  [[0.17177914110429449, 0.18404907975460122, 0....           Art_practice   
3  [[0.22162162162162163, 0.21891891891891893, 0....  AI_models_familiarity   
4  [[0.18181818181818182, 0.19913419913419914, 0....                    Age   

   ddof1          H     p-unc                 Source  ddof1          H  \
0      1   0.067037  0.795701                 Artist      1   0.067037   
1      2  19.650716  0.000054        Gender_identity      2  19.650716   
2     13  17.971415  0.158608           Art_practice     13  17.971415   
3      4   6.531461  0.162819  AI_models_familiarity      4   6.531461   
4      3   2.547225  0.466817                    Age      3   2.547225   

      p-unc  
0  0.795701  
1  0.000054  
2  0.158608  
3  0.162819  
4  0.466817